# Project-wide Gradle settings.
#
# Configuration should be synced with [/gradle/build-logic/gradle.properties],
# since Gradle properties are not passed to included builds.

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx5120m
org.gradle.parallel=true
org.gradle.workers.max=5

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

android.useAndroidX=true

kotlin.stdlib.default.dependency=false
