package io.github.samfun75.gradle.tasks

import io.github.samfun75.gradle.api.ContentWarning
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateManifestTask : DefaultTask() {
    @get:Input
    abstract val extensionName: Property<String>

    @get:Input
    abstract val qualifiedName: Property<String>

    @get:Input
    abstract val contentWarning: Property<ContentWarning>

    @get:Input
    abstract val extensionLib: Property<String>

    @get:Input
    abstract val versionId: Property<Int>

    @get:Input
    abstract val sourceNames: ListProperty<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val name = extensionName.get().escapeXml()
        val warning = contentWarning.get()
        val nsfw = if (warning == ContentWarning.SAFE) "0" else "1"
        val names = sourceNames.get().joinToString(";").escapeXml()

        outputFile.get().asFile.apply { parentFile.mkdirs() }.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by proj.plugins.extension - do not edit by hand. -->
            |<manifest xmlns:android="http://schemas.android.com/apk/res/android">
            |    <uses-feature android:name="tachiyomi.animeextension" />
            |    <application
            |        android:allowBackup="false"
            |        android:icon="@mipmap/ic_launcher"
            |        android:label="Aniyomi: $name">
            |        <meta-data android:name="tachiyomi.animeextension.class" android:value=".${qualifiedName.get()}" />
            |        <meta-data android:name="tachiyomi.animeextension.nsfw" android:value="$nsfw" />
            |        <meta-data android:name="tachiyomi.animeextension.versionId" android:value="${versionId.get()}" />
            |        <meta-data android:name="tachiyomi.animeextension.names" android:value="$names" />
            |        <meta-data android:name="aniyomix.name" android:value="$name" />
            |        <meta-data android:name="aniyomix.contentWarning" android:value="${warning.ordinal}" />
            |        <meta-data android:name="aniyomix.extensionLib" android:value="${extensionLib.get()}" />
            |    </application>
            |</manifest>
            |
            """.trimMargin(),
        )
    }
}

private fun String.escapeXml() = replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;")
